---
- hosts: masterdb
  become: true
  vars:
    mariadb_bind_address: '0.0.0.0'
    mariadb_root_password: 'password123'
    mariadb_users:
      - name: appusr
        password: 'password123'
        priv: "myappdb.*:ALL,GRANT"
        host: "%"
    mariadb_custom_cnf:
      mysqld:
        general-log:
        general-log-file: queries.log
        log-output: file
  roles:
    - bertvv.mariadb
