---
- hosts: all
  tasks:
  - name: install Docker
    yum:
      name: docker
      state: present
      update_cache: true

  - name: start Docker
    service:
      name: docker
      state: started

  - name: disable SELinux
    command: setenforce 0

  - name: disable SELinux on reboot
    selinux:
       state: disabled

  - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
    sysctl:
       name: net.bridge.bridge-nf-call-ip6tables
       value: 1
       state: present

  - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
    sysctl:
       name: net.bridge.bridge-nf-call-iptables
       value: 1
       state: present

  - name: add Kubernetes' YUM repository
    yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes


  - name: install kubelet
    yum:
        name: kubelet-1.11.3
        state: present
        update_cache: true

  - name: install kubeadm
    yum:
        name: kubeadm-1.11.3
        state: present



- hosts: workers
  become: yes
  tasks:
  - name: kubelet extra args
    lineinfile:
        path: /etc/sysconfig/kubelet
        regexp: '^KUBELET_EXTRA_ARGS='
        line: 'KUBELET_EXTRA_ARGS=--cloud-provider=external' 
    when: fancy is defined

  - name: start kubelet
    service:
       name: kubelet
       enabled: yes
       state: started

- hosts: masters
  become: yes
  tasks:
  - name: install kubectl
    yum:
        name: kubectl-1.11.3
        state: present

  - name: start kubelet
    service:
       name: kubelet
       enabled: yes
       state: started

  - name: install git
    yum:
        name: git
        state: present

